name: gol
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - ipython
  - jupyter
  - numpy
  - scipy
  - matplotlib
  - ipympl
  - iminuit
  - pandas
  - resample
  - seaborn
  - scikit-learn
  - tabulate
  - tqdm
  - uncertainties
  - statsmodels
  - flake8
  - jacobi